name: Update Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 08:00AM and 08:00PM UTC
    - cron: '0 8,20 * * *'

jobs:
  update-readme:
    name: Update this repo's README with latest WaKa time stats
    runs-on: ubuntu-latest
    steps:
      - uses: izdrail/stats.izdrail.com@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"
          SHOW_OS: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          LOCALE: "en"
